spring.application.name=COVID 19 

spring.datasource.url=jdbc:mysql://localhost:3306/covid_project
spring.datasource.username=root
spring.datasource.password=nikhil@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

